mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from django.views.decorators.cache import cache_page

from .views import (
    ShopIndexView,
    GroupsListView,

    ProductDetailsView,
    ProductsListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,

    OrderDetailsView,
    OrdersListView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,

    ProductsDataExportView,

    OrdersDataExportView,

    ProductViewSet,
    OrderViewSet,

    UserOrderListsView,
    UserOrdersDataExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name='index'),
    path("groups/", GroupsListView.as_view(), name='groups_list'),

    path("api/", include(routers.urls)),

    path("products/", ProductsListView.as_view(), name='products_list'),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name='product_details'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name='product_update'),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name='product_delete'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),

    path("products/export/", ProductsDataExportView.as_view(), name='products-export'),

    path("orders/", OrdersListView.as_view(), name='orders_list'),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name='order_details'),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name='order_update'),
    path("orders/<int:pk>/archive/", OrderDeleteView.as_view(), name='order_delete'),
    path("orders/create/", OrderCreateView.as_view(), name='order_create'),

    path("orders/export/", OrdersDataExportView.as_view(), name='orders-export'),

    path("user_orders/<int:user_id>/", UserOrderListsView.as_view(), name='user-orders-list'),
    path("user_orders/<int:user_id>/export/",
         UserOrdersDataExportView.as_view(), name='user-orders-export'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

from django.utils.translation import gettext_lazy as _


def product_preview_directly_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар, который можно
    продавать в Интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ['name']
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directly_path)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + '...'

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


class Order(models.Model):
    """
    Модель Order представляет заказ, который можно
    сделать в Интернет-магазине.

    Товары тут: :model:`shopapp.Product`
    """
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def __str__(self) -> str:
        return f"Order(pk={self.pk})"

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
Base Title
        {% endblock %}
    </title>
</head>
<body>

{% block body %}
Base Body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>

<div>
    {% now 'l' as current_weekday %}
    {% translate 'Today is' %}: {{ current_weekday }}
</div>

</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}Create order{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create</button>
    </form>
    </div>

    <div>
    <a href="{% url 'shopapp:products_list' %}">Back</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}Create product{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create</button>
    </form>
    </div>

    <div>
    <a href="{% url 'shopapp:products_list' %}">Back</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    </div>

    {% if not groups %}
    	<h3>No groups yet </h3>
    {% else %}
        <ul>

        {% for group in groups %}
            <div>{{ group.name }}</div>
            <ul>
            {% for permission in group.permissions.all %}
            	<li>{{ permission.name }}</li>
                (<code>{{ permission.codename }}</code>)
            {% endfor %}
            </ul>
            {% endfor %}
        </ul>
    {% endif %}
    
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}Confirm archive Order #{{ order.pk }}{% endblock %}

{% block body %}
    <h1>Are you sure to archive Order #{{ order.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}">Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %} Orders list {% endblock %}

{% block body %}
    <h1>Orders: </h1>
    {% if orders %}
        <div>
        {% for order in orders %}
        	<div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Details #{{ order.pk }}</a></p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Product in order:
                    <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for $ {{ product.price }}</li>
                    {% endfor %}

                    </ul>
                </div>
                </div>
        {% endfor %}
        
        </div>

    {% else %}
        <h3>No orders yet</h3>
    {% endif %}

    <br>
        <div>
            <a href="{% url 'shopapp:order_create' %}">Create a new order</a>
        </div>
    <br>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}Update Order{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to {{ object.pk }}</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}Confirm archive {{ object.name }}{% endblock %}

{% block body %}
    <h1>Are you sure to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}Create Product{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Product' %}#{{ product.pk }}
{% endblock %}

{% block body %}
            <h1>{% translate 'Product' %}: <strong>{{ product.name }}</strong></h1>
            <div>
                <div>{% translate 'Created by' %}: {{ user.username }}</div>
                <div>{% translate 'Descriptioh' %}: <em>{{ product.description }}</em></div>
                <div>{% translate 'Price' %}: {{ product.price }}</div>
                <div>{% translate 'Discount' %}: {{ product.discount }}</div>
                <div>{% translate 'Archived' %}: {{ product.archived }}</div>
                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
        </div>
            <br>
            <div>
            {% blocktranslate count previews_count=1 %}
                There is only one preview
            {% plural %}
                There are {{ previews_count }} previews
            {% endblocktranslate %}
        </div>

        <br>
        <div>
                {% if perms.shopapp.change_product and perms.shopapp.add_product %}
                <a href="{% url 'shopapp:product_update' pk=object.pk %}">{% translate 'Update product' %}</a>
                {% endif %}
            </div>
            <br>
            <div>
                <a href="{% url 'shopapp:product_delete' pk=object.pk %}">{% translate 'Archive product' %}</a>
            </div>
            <br>
            <div>
                <a href="{% url 'shopapp:products_list' %}">{% translate 'Back to products list' %}</a>
            </div>
        <br>

{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
      Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %} {% translate 'Products list' %} {% endblock %}

{% block body %}
<h1>{% translate 'Products' %}</h1>
    {% if products %}
        <div>
            {% blocktranslate count products_count=products|length %}
                There is only one product.
            {% plural %}
                There are {{ products_count }} products.
            {% endblocktranslate %}
        </div>

        <div>
        {% for product in products %}
        	<div>
                <p>{% translate 'Name' context 'product name' %}: <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></p>
                <p>{% translate 'Price' %}: {{ product.price }}</p>
                {% translate 'no discount' as no_discount %}
                <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

                {% if product.preview %}
            	    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}

            </div>
        {% endfor %}
        
        </div>
    	{% else %}
        <h3>{% translate 'No products yet' %}</h3>
    {% endif %}

    <div>
    {% if perms.shopapp.view_product %}
        <a href="{% url 'shopapp:product_create' %}">{% translate 'Create a new product' %}</a>
    {% endif %}
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}

    Shop Index

{% endblock %}

{% block body %}

    <h1>Hello Shop Index!</h1>

    <div>
    <ul>
        {% for name, price in products %}
        	<li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
            {% if name|length_is:'7' %}
                <span>Lucky product!</span>
            {% endif %}
        {% empty %}
            No products here.
        {% endfor %}
        
    </ul>
    </div>

    <div>
    You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
    </div>

    <div>
    Time Running: {{ time_running }}
    </div>

    {% cache 100 lorem %}
        <div>
        {% lorem 3 p random %}
        </div>
    {% endcache %}

{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %} User Orders list {% endblock %}

{% block body %}

    {% if request.user.is_authenticated %}
        <h1>{{ owner.username }}'s orders</h1>
            <div>
                {% if user_orders %}
                    {% cache 60 user_orders owner.user_id %}
                        {% for order in user_orders %}
                            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Order #{{ order.pk }}</a></p>
                        {% endfor %}
                    {% endcache %}
                {% else %}
                    <p>No user's orders yet</p>
                {% endif %}
            </div>
    {% else %}
        <p>Sorry, you must <a href="{% url 'myauth:login' %}">login</a> first.</p>
    {% endif %}

{% endblock %}