mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
                    # set_cookie_view,
                    get_cookie_view,
                    # set_session_view,
                    # get_session_view,
                    MyLogoutView,
                    AboutMeView,
                    RegisterView,
                    ProfileUpdateView,
                    ProfilesListView,
                    ProfileDetailsView,
                    # FooBarView,
                    HelloView,
)

app_name = "myauth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login'),

    path("cookie/get/", get_cookie_view, name='cookie-get'),
    # path('cookie/set/', set_cookie_view, name='cookie-set'),
    #
    # path("session/set/", set_session_view, name='session-set'),
    # path('session/get/', get_session_view, name='session-get'),

    path('hello/', HelloView.as_view(), name='hello'),

    path('logout/', MyLogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),

    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('update/<int:pk>/', ProfileUpdateView.as_view(), name='update'),

    path('list/', ProfilesListView.as_view(), name='users-list'),
    path('details/<int:pk>/', ProfileDetailsView.as_view(), name='user-details'),

    # path('foo-bar/', FooBarView.as_view(), name="foo-bar"),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models
from shopapp.models import Order


def profile_avatar_directly_path(instance: "Profile", filename: str) -> str:
    return "profiles/profile_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directly_path)

mysite/myauth/views.py
from random import random

from django.contrib.auth.decorators import (login_required,
                                            permission_required,
                                            user_passes_test)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views.generic import (TemplateView,
                                  CreateView,
                                  UpdateView,
                                  ListView,
                                  DetailView)
from django.views import View
from .models import Profile
from django.utils.translation import gettext_lazy as _, ngettext

from django.views.decorators.cache import cache_page


class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class ProfilesListView(ListView):
    template_name = 'myauth/users_list.html'
    model = User
    context_object_name = "users"


class ProfileDetailsView(DetailView):
    template_name = 'myauth/user-details.html'
    model = User
    context_object_name = "user"


class ProfileUpdateView(PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Profile
    fields = 'bio', 'avatar'
    template_name_suffix = "_update_form"

    permission_required = "myauth.change_profile"

    def test_func(self):
        if self.request.user.is_staff or self.request.user.id == self.get_object().user.id:
            return True

        has_edit_perm = self.request.user.has_perm("myauth.change_profile")

        return has_edit_perm

    def get_success_url(self):
        return reverse(
            "myauth:user-details",
            kwargs={"pk": self.get_object().user.id},
        )

    # def get_object(self, queryset=None):
    #     return self.request.user.profile


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)

        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')
        else:
            return render(request, 'myauth/login.html')

    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {"error": "Invalid Login Credentials"})


# @user_passes_test(lambda u: u.is_super)
# def set_cookie_view(request: HttpRequest) -> HttpResponse:
#     response = HttpResponse("Cookie set")
#     response.set_cookie('fizz', 'buzz', max_age=3600)
#     return response
#
#
@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default_value')
    return HttpResponse(f"Cookie value: {value!r} + {random()}")
#
#
# @permission_required("myauth.view_profile", raise_exception=True)
# def set_session_view(request: HttpRequest) -> HttpResponse:
#     request.session["foobar"] = "spameggs"
#     return HttpResponse('Session Set!')
#
#
# @login_required
# def get_session_view(request: HttpRequest) -> HttpResponse:
#     value = request.session.get("foobar", "default")
#     return HttpResponse(f"Session value: {value!r}")


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

# class FooBarView(View):
#     def get(self, request: HttpRequest) -> JsonResponse:
#         return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}My profile{% endblock %}

{% block body %}
    <h1>My profile</h1>
    {% if user.is_authenticated %}

        <h2>Details</h2>

        {% if user.profile.avatar %}
            <p>Avatar: </p>
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
        {% else %}
            <i>No avatars yet</i>
        {% endif %}
        <br>

        <p>Username: {{ user.username }}</p>
        <p>Bio: <i>{{ user.profile.bio }}</i></p>
        <br>
        <p><a href="{% url 'shopapp:user-orders-list' request.user.id %}">My orders</a></p>
        <br>
        <p><a href="{% url 'myauth:update' request.user.id %}">Update profile</a></p>
        <br>
        <p><a href="{% url 'myauth:users-list' %}">Users List</a></p>
        <br>
        <p><a href="{% url 'myauth:logout' %}">Logout</a></p>

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %} 
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}

    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>

    </form>

    <br>
    <p><a href="{% url 'myauth:register' %}">Register</a></p>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}Update Profile{% endblock %}

{% block body %}
    <h1>Update profile</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    </div>
    <br>
    <div>
        <a href="{% url 'myauth:users-list' %}">Back to users list</a>
    </div>
    <br>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}Register{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user-details.html
{% extends 'myauth/base.html' %}

{% block title %} Users list {% endblock %}

{% block body %}
    <h1>User Details: {{ user.username }}</h1>

    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="avatar">
    {% endif %}
    <br>

    <p>Name: {{ user.username }}</p>
    <p>Bio: {{ user.profile.bio }}</p>
    <br>
    {% if request.user.is_staff or perms.myauth.change_profile %}
        <p><a href="{% url 'myauth:update' pk=user.profile.pk %}">Update this profile</a></p>
        <br>
    {% endif %}
    <p><a href="{% url 'myauth:users-list' %}">Back to users list</a></p>

{% endblock %}

mysite/myauth/templates/myauth/users_list.html
{% extends 'myauth/base.html' %}

{% block title %} Users list {% endblock %}

{% block body %}
    <h1>Users list</h1>
        {% if users %}
            <div>
            {% for user in users %}
                <div>
                    {% if user.profile.avatar %}
                        <a href="{% url 'myauth:user-details' pk=user.pk %}"><img src="{{ user.profile.avatar.url }}" alt="avatar"></a>
                    {% endif %}
                    <p>Name: <a href="{% url 'myauth:user-details' pk=user.pk %}">{{ user.username }}</a></p>
                    <p>Bio: {{ user.profile.bio }}</p>
                </div>
                <br>
            {% endfor %}
                <br>
                <p><a href="{% url 'myauth:about-me' %}">Back to my profile</a></p>
            </div>
            {% else %}
            <h3>No users yet</h3>
        {% endif %}

{% endblock %}